<?php

class Item
{
    public $weight;
    protected $color;

    public function __construct($color)
    {
        $this->color = $color;
        echo 'Я родился!!';
    }

    public function showColor()
    {
        echo 'Мой цвет: ' . $this->color;
    }
}

class Table extends Item
{
    public $legs;

    public function showColor()
    {
        echo 'Я - стол. ';
        parent::showColor(); // TODO: Change the autogenerated stub
    }
}

$table = new Table('black');
$table->weight = 14;
$table->legs = 4;

$table->showColor();
